#!/bin/bash

#array

myArray=( 1 2 sohan "hello" )

echo "the values in array are ${myArray[*]}"

echo the third value in the array is ${myArray[3]} # retrieves the 3 rd element in the array in array index number starts from 0

echo length of the array is ${#myArray[*]}   #-- This gives the length of the array '#' has to be added in the start

echo ${myArray[*]:2:3}  # this specifies if we want specific value of array in this example the array will take value from index 2 to upto 3 numbers after that

# to update an array use the following

myArray+=( 5 6.7 4 9 )

echo ${myArray[*]:2:3}

#below command shows declaring key value pair in array

#to use key value pair in array first we have to declare an array using declare -A arrayname

declare -A Array

#after declaring in array you have to give the key inside the [ ] and followed by an equals a
nd the value

Array=( [name]=sohan [age]=21 )

#here when the key name is called it will return the value associated with it.

echo the name is ${Array[name]}
