#!/bin/bash

echo Welcome to simple password generator

sleep 1   #--------it gives 1s of break after the first line.

echo Please enter the length of the password
read pass_ln  # ---------------------- taking input of password length.

for p in $(seq 2 );      #----------------seq 2 means how many password to be generated if you want to generate 1 password you can give it one.
do
        openssl rand -base64 48 | cut -c1-$pass_ln  #------------------------rand means random, base64 is used to convert binary to readable format, c1 means column 1.
done
