#!/bin/bash

#simple calculations
#to perform any mathematical operations you have to use let before the vairable

echo enter two numbers

read x y

let multi=x*y
let sum=x+y
let diff=x-y
let div=x/y




echo "sum= $sum"

echo " multi= $multi"

echo "difference= $diff"

echo "division= $div"

# you can use one more way to perform operations that is using double braces

echo enter two numbers

read a b

echo sum is $(($a+b))
