#!/bin/bash

#simple shell scripting for case operation using menu method

echo "this is a Case script"

echo -e

echo "a) To see current date"

echo "b) To see current working Directory"

echo "c) To check the uptime of system"

read choice #this allows to enter a choice

case $choice in  #the entered choice wil check for the letter associated with it and perform the operation
        a) echo "Todays date is :$(date +%D)";;
        b) echo "Current working directory is :$(pwd)";;
        c) echo "System uptime is :$(uptime)";;
        *) echo "Wrong input";;
esac
