#!/bin/bash

#to define a function
function myfun {
        echo "hello all"
}


#to call a functio just righ the function name

myfun

#arguments in function
echo -ne ""

echo "**********This is a simple calculator***********"

echo -ne ""

calculator(){
        local num1=$1  # $1 and numbers are used to take arguments in a function
        local num2=$2
        let sum=$num1+$num2
        let mult=$num1*$num2
        let diff=$num1-$num2
        let dib=$num1/$num2
        echo Sum is $sum
        echo Multiplication is $mult
        echo difference is $diff
        echo divison is $dib
}

calculator 10 20       # the value of the arguments are given here when you call the function
