#!/bin/bash

#AND operator &&

read -p "Enter your age: " age

read -p "enter your citizenship: " country

if [[ $age -ge 18 ]] && [[ $country == "India" ]]
then
        echo "You are eligible to vote"
else
        echo "You are not eligible"
fi

#OR operator ||

read -p "Enter your age: " age

read -p "enter your citizenship: " country

if [[ $age -ge 18 ]] || [[ $country == "India" ]]
then
        echo "You are eligible to vote"
else
        echo "You are not eligible"
fi

#combining both the operators

read -p "Enter your age : " age

[[ age -ge 18 ]] && echo "Adult" || echo "Minor"
