#!/bin/bash

#to declare a string you can declare it inside double quotes ""

mystring="Hey Hello!!"

#to find the length of the string use the below command

mystringLength=${#mystring} # here the string lenth will be stored in the new variable mystringLength '#' is used for length in shell scripting

echo " length of my string is $mystringLength"

#to convert a string to upper case you have to use ^^ as mentioned below

echo "upper case is ${mystring^^}"

#to convert a string to lower case you hve to use ,, as mentioned below

echo "lower case is ${mystring,,}"

# to replafce a word in a string

#create a another variable where you ca store the replaced string

#first word is the word which you want to be replaced / second word is the word which you want to include in that place
replacedstring=${mystring/Hello/Sohan}

echo "replaced string is ${replacedstring}"

# to slice the string

slice=${mystring:3:6}

#here in the above command we are creating a variable where we will be assigning the sliced string, the first number indicates index  number we have to start slicing second number indicates the length till where it needs to be sliced

# the above command will print hello

echo " sliced string is ${slice}"
